### ISSUE TITLE
Exited process may not be reported as terminated until children exit

### ISSUE THREAD

**Issue by gusostow** [alexhsamuel/procstar#32]
I noticed that processes that are intended to daemonize are still being tracked by procstar until they exit. 

```sh
$ procstar --print - <<EOF
{
    "specs": {
        "foo": {
            "argv": [
                "/usr/bin/bash", "-c", "sleep 10 &"
            ]
        }
    }
}
EOF
```

I wasn't sure if this was intentional but the elapsed time matches the main processes exiting.  From poking around a little, I think the error pipe is getting held open by child processes that aren't closing the write end. https://github.com/alexhsamuel/procstar/blob/a8f6cbcf220447bd98189cd257e4fe7ef184a256/src/procs.rs#L487. Can the pipe be closed on exec if it isn't needed after that point?

**Comment by alexhsamuel** [comment]
Fixed on main, which contains changes that are not ready to release yet.  LMK if you need me to backport this to the last release.

**Comment by alexhsamuel** [comment]
BTW your example is not how you daemonize, though the bug you're reporting was clear.

**Comment by gusostow** [comment]
You mean that you need to redirect stdout/err and do the whole double fork thing?

**Comment by gusostow** [comment]
A backport would be helpful, thanks, so we don't need to be careful about jobs that are meant to run in the background.

**Comment by alexhsamuel** [comment]
Here you go: https://github.com/alexhsamuel/procstar/releases/tag/v0.2.5
